# 1️⃣ .github/workflows/ci-cd.yml
name: Go Multi-Service CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  lint-vet-test:
    name: Lint, Vet, Test
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        service: [user-service, order-service]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run Lint
        run: |
          cd ${{ matrix.service }}
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Run Vet
        run: |
          cd ${{ matrix.service }}
          go vet ./...

      - name: Run Tests
        run: |
          cd ${{ matrix.service }}
          go test ./... -cover

  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: lint-vet-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Services
        run: |
          for svc in user-service order-service; do
            echo "Building and pushing $$svc..."
            docker build -f $$svc/Dockerfile -t your_registry/$$svc:latest $$svc
            docker push your_registry/$$svc:latest
          done
