services:
  omniapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omniapp
    hostname: omniapp
    image: ${PROJECT_NAME:-omniapp}:latest  # Set default to avoid blank variable
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
