services:
  omniapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: omniapi-prod
    hostname: omniapi
    image: ${PROJECT_NAME:-omniapi}:prod
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:ro  # Read-only for security
    environment:
      # Laravel Application Settings
      APP_NAME: Laravel
      APP_ENV: production
      APP_KEY: ${APP_KEY}  # Set via environment variable or secret
      APP_DEBUG: "false"
      APP_URL: http://localhost:80
      APP_URL_2: http://api.omniinformatica.com.br
      LOG_CHANNEL: stack

      # Omni PreAtendimento (MySQL)
      DB_HOST_PA: 192.168.0.4
      DB_PORT_PA: 3306
      DB_DATABASE_PA: omni_produtos
      DB_USERNAME_PA: root
      DB_PASSWORD_PA: ${DB_PASSWORD_PA}  # Set via environment variable or secret

      # Banco de Notas Fiscais (KGB, MySQL)
      DB_HOST_KBB: 192.168.0.46
      DB_PORT_KBB: 3306
      DB_DATABASE_KBB: omni_db
      DB_USERNAME_KBB: root
      DB_PASSWORD_KBB: ${DB_PASSWORD_KBB}  # Set via environment variable or secret

      # Omni Curitiba (Firebird)
      DB_CONNECTION: firebird
      DB_HOST: 192.168.0.15
      DB_PORT: 3050
      DB_DATABASE: 'C:\Program Files (x86)\CompuFour\Clipp\Base\CLIPP.FDB'
      DB_USERNAME: SYSDBA
      DB_PASSWORD: ${DB_PASSWORD}  # Set via environment variable or secret
      DB_CHARSET: WIN1252

      # Omni Londrina (Firebird)
      DB_HOST_LONDRINA: 192.168.1.2
      DB_DATABASE_LONDRINA: 'C:\Program Files (x86)\CompuFour\Clipp\Base\CLIPP.FDB'

      # Omni Natal (Firebird)
      DB_HOST_NATAL: 192.168.2.2
      DB_DATABASE_NATAL: 'C:\Program Files (x86)\CompuFour\Clipp\Base\CLIPP.FDB'

      # Omni Recife (Firebird)
      DB_HOST_RECIFE: 192.168.3.2
      DB_DATABASE_RECIFE: 'C:\Program Files (x86)\CompuFour\Clipp\Base\CLIPP.FDB'

      # Omni Aracaju (Firebird)
      DB_HOST_ARACAJU: 192.168.4.2
      DB_DATABASE_ARACAJU: 'C:\Program Files (x86)\CompuFour\Clipp\Base\CLIPP.FDB'

      # Laravel Drivers
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

      # Redis (not used based on QUEUE_CONNECTION=sync, but included for completeness)
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      # Mail Settings
      MAIL_MAILER: smtp
      MAIL_HOST: mail.omniinformatica.com.br
      MAIL_PORT: 587
      MAIL_USERNAME: sendmail
      MAIL_PASSWORD: ${MAIL_PASSWORD}  # Set via environment variable or secret
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: null
      MAIL_FROM_NAME: "${APP_NAME}"

      # AWS (empty in .env, included for completeness)
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: ""

      # Pusher (empty in .env, included for completeness)
      PUSHER_APP_ID: ""
      PUSHER_APP_KEY: ""
      PUSHER_APP_SECRET: ""
      PUSHER_APP_CLUSTER: mt1
      MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
      MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

      # Firebase and GSX
      URL_FIREBASE_APP: https://omni-5ce42-default-rtdb.firebaseio.com/
      GSX_URL: https://gsx2.apple.com/

      # Nota Fiscal
      NF_SERIE: 1
      NF_MODELO: 55
    ports:
      - "8012:80"
    networks:
      - omnidev
    secrets:
      - app_key
      - db_password_pa
      - db_password_kbb
      - db_password
      - mail_password

secrets:
  app_key:
    file: ./secrets/app_key.txt
  db_password_pa:
    file: ./secrets/db_password_pa.txt
  db_password_kbb:
    file: ./secrets/db_password_kbb.txt
  db_password:
    file: ./secrets/db_password.txt
  mail_password:
    file: ./secrets/mail_password.txt

networks:
  omnidev:
    driver: bridge
